name: Commit Lottery

on: push

jobs:
  commit-lottery:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate daily winning SHA
      id: generate_sha
      run: |
        echo "WINNING_SHA=$(date -u +%Y%m%d | sha256sum | head -c 7)" >> $GITHUB_ENV
        echo "Winning daily SHA: $WINNING_SHA"

    - name: Get current commit SHA
      id: get_commit_sha
      run: echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

    - name: Check commit lottery
      run: |
        WINNING_SHA=${{ env.WINNING_SHA }}
        COMMIT_SHA=${{ env.COMMIT_SHA }}
        COMMIT_SHA=${COMMIT_SHA:0:7}

        echo "Winning SHA: $WINNING_SHA"
        echo "Commit SHA: $COMMIT_SHA"

        MATCH_COUNT=0

        for (( i=0; i<${#WINNING_SHA}; i++ )); do
            if [[ ${WINNING_SHA:$i:1} == ${COMMIT_SHA:$i:1} ]]; then
                (( MATCH_COUNT++ ))
            fi
        done

        echo "Match Count: $MATCH_COUNT"

        if [ "$MATCH_COUNT" -ge 5 ]; then
            echo "You won the first prize!"
        elif [ "$MATCH_COUNT" -eq 4 ]; then
            echo "You won the second prize!"
        elif [ "$MATCH_COUNT" -eq 3 ]; then
            echo "You won the third prize!"
        else
            echo "No prize this time."
        fi

        exit 0
